(() => {
'use strict';
const QUESTIONS = Array.isArray(window.QUESTIONS) ? window.QUESTIONS : [];
const QUESTION_COUNT = 201;
const DATA_HASH = 'e5ea4d584d0169f58f7d6c5d9699dd5a0960f9f71fb0170451424271fa14dad1';
const STORAGE_KEY = 'pharm201-state-v2';
const LEGACY_PROGRESS_KEY = 'pharm201-progress-v1';
const BACKUP_VERSION = 2;
const $ = id => document.getElementById(id);
const els = {save:$('saveState'),notice:$('storageNotice'),total:$('totalCount'),known:$('knownCount'),unknown:$('unknownCount'),unseen:$('unseenCount'),search:$('searchInput'),status:$('statusFilter'),category:$('categoryFilter'),order:$('orderSelect'),reshuffle:$('reshuffleButton'),match:$('matchCount'),empty:$('emptyState'),resetFilters:$('resetFiltersButton'),card:$('questionCard'),number:$('questionNumber'),categoryText:$('questionCategory'),progress:$('questionProgress'),question:$('questionText'),toggle:$('answerToggle'),answerPanel:$('answerPanel'),answer:$('answerText'),supplement:$('supplementText'),origin:$('originText'),judgeRow:$('judgeRow'),knownButton:$('knownButton'),unknownButton:$('unknownButton'),currentState:$('currentState'),prev:$('prevButton'),next:$('nextButton'),jumpInput:$('jumpInput'),jumpButton:$('jumpButton'),exportButton:$('exportButton'),importInput:$('importInput'),resetButton:$('resetButton'),message:$('message')};
const validIds = new Set(QUESTIONS.map(q => String(q.id)));
const validCategories = new Set(QUESTIONS.map(q => q.category));
let storageOK = true;
let answerVisible = false;
let filtered = [];
let currentIndex = 0;

function defaultState() { return {progress:{},statusFilter:'all',category:'all',order:'number',search:'',shuffleIds:[],currentId:1}; }
function normalizeText(v) { return String(v ?? '').normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim(); }
function makeShuffle(ids, randomFn=Math.random) { const a=[...ids]; for(let i=a.length-1;i>0;i--){const j=Math.floor(randomFn()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; }
function validPermutation(a) { return Array.isArray(a)&&a.length===QUESTIONS.length&&new Set(a.map(Number)).size===QUESTIONS.length&&a.every(id=>validIds.has(String(Number(id)))); }
function sanitizeProgress(value) { const out={}; if(!value||typeof value!=='object'||Array.isArray(value)) return out; for(const [id,status] of Object.entries(value)) if(validIds.has(String(id))&&(status==='known'||status==='unknown')) out[String(id)]=status; return out; }
function sanitizeState(raw) { const d=defaultState(); if(!raw||typeof raw!=='object'||Array.isArray(raw)) return d; d.progress=sanitizeProgress(raw.progress||raw.status); if(['all','unseen','unknown','known'].includes(raw.statusFilter||raw.filter)) d.statusFilter=raw.statusFilter||raw.filter; if(raw.category==='all'||validCategories.has(raw.category)) d.category=raw.category; if(['number','shuffle'].includes(raw.order)) d.order=raw.order; if(typeof raw.search==='string') d.search=raw.search.slice(0,300); d.shuffleIds=validPermutation(raw.shuffleIds)?raw.shuffleIds.map(Number):makeShuffle(QUESTIONS.map(q=>q.id)); if(validIds.has(String(Number(raw.currentId)))) d.currentId=Number(raw.currentId); return d; }
function loadState() {
  try { localStorage.setItem('__pharm_test__','1'); localStorage.removeItem('__pharm_test__'); }
  catch(e) { storageOK=false; els.notice.hidden=false; els.notice.textContent='端末保存が利用できない環境です。この画面を閉じる前にバックアップを書き出してください。'; const d=defaultState();d.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id));return d; }
  const raw=localStorage.getItem(STORAGE_KEY);
  if(raw){try{return sanitizeState(JSON.parse(raw));}catch(e){localStorage.removeItem(STORAGE_KEY);els.notice.hidden=false;els.notice.textContent='壊れた保存データを初期化し、正常な状態に修復しました。';}}
  const legacy=localStorage.getItem(LEGACY_PROGRESS_KEY);
  if(legacy){try{const d=defaultState();d.progress=sanitizeProgress(JSON.parse(legacy));d.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id));return d;}catch(e){localStorage.removeItem(LEGACY_PROGRESS_KEY);}}
  const d=defaultState(); d.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id)); return d;
}
let state=loadState();
function saveState() { state=sanitizeState(state); try{if(storageOK)localStorage.setItem(STORAGE_KEY,JSON.stringify(state));els.save.textContent=storageOK?'保存済み':'一時保存';}catch(e){storageOK=false;els.save.textContent='一時保存';els.notice.hidden=false;els.notice.textContent='端末保存に失敗しました。バックアップを書き出してください。';} updateStats(); }
function getStatus(q) { return state.progress[String(q.id)]||'unseen'; }
function filterQuestions(list, options, progressMap) { const needle=normalizeText(options.search); return list.filter(q=>{const status=progressMap[String(q.id)]||'unseen';if(options.status!=='all'&&status!==options.status)return false;if(options.category!=='all'&&q.category!==options.category)return false;if(!needle)return true;return normalizeText([q.id,q.category,q.question,q.answer,q.supplement,q.origin].join(' ')).includes(needle);}); }
function sequenceFor(list) { if(state.order==='number') return [...list].sort((a,b)=>a.id-b.id); if(!validPermutation(state.shuffleIds)) state.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id)); const rank=new Map(state.shuffleIds.map((id,i)=>[id,i])); return [...list].sort((a,b)=>rank.get(a.id)-rank.get(b.id)); }
function applyFilters({preserveCurrent=true,preferredIndex=null}={}) { const oldId=preserveCurrent?state.currentId:null; const opts={search:state.search,status:state.statusFilter,category:state.category}; filtered=sequenceFor(filterQuestions(QUESTIONS,opts,state.progress)); let idx=oldId==null?-1:filtered.findIndex(q=>q.id===oldId); if(idx<0) idx=preferredIndex==null?0:Math.min(Math.max(0,preferredIndex),Math.max(0,filtered.length-1)); currentIndex=idx; if(filtered.length) state.currentId=filtered[currentIndex].id; els.match.textContent=String(filtered.length); saveState(); render(); }
function resetReveal() { answerVisible=false;els.answerPanel.hidden=true;els.judgeRow.hidden=true;els.toggle.textContent='解答を見る';els.toggle.setAttribute('aria-expanded','false'); }
function render() { const has=filtered.length>0;els.card.hidden=!has;els.empty.hidden=has;els.prev.disabled=!has||currentIndex<=0;els.next.disabled=!has||currentIndex>=filtered.length-1;if(!has)return;const q=filtered[currentIndex];state.currentId=q.id;resetReveal();els.number.textContent=`No.${q.id}`;els.categoryText.textContent=q.category;els.progress.textContent=`${currentIndex+1} / ${filtered.length}`;els.question.textContent=q.question;els.answer.textContent=q.answer;els.supplement.textContent=q.supplement;els.origin.textContent=`出典：${q.origin}`;els.jumpInput.value=String(q.id);updateJudgeState(q);}
function updateJudgeState(q) { const s=getStatus(q);els.knownButton.classList.toggle('active',s==='known');els.unknownButton.classList.toggle('active',s==='unknown');els.currentState.textContent=s==='known'?'判定：わかった':s==='unknown'?'判定：分からなかった':'未学習'; }
function updateStats() { let known=0,unknown=0;for(const q of QUESTIONS){const s=getStatus(q);if(s==='known')known++;else if(s==='unknown')unknown++;}els.total.textContent=String(QUESTIONS.length);els.known.textContent=String(known);els.unknown.textContent=String(unknown);els.unseen.textContent=String(QUESTIONS.length-known-unknown); }
function toggleAnswer() { answerVisible=!answerVisible;els.answerPanel.hidden=!answerVisible;els.judgeRow.hidden=!answerVisible;els.toggle.textContent=answerVisible?'解答を隠す':'解答を見る';els.toggle.setAttribute('aria-expanded',String(answerVisible)); }
function judge(status) { if(!answerVisible||!filtered.length)return;const q=filtered[currentIndex];const oldIndex=currentIndex;state.progress[String(q.id)]=status;const stays=filterQuestions([q],{search:state.search,status:state.statusFilter,category:state.category},state.progress).length===1;if(stays&&oldIndex<filtered.length-1){state.currentId=filtered[oldIndex+1].id;saveState();applyFilters({preserveCurrent:true});}else if(stays){saveState();render();}else applyFilters({preserveCurrent:false,preferredIndex:oldIndex}); }
function move(delta) { if(!filtered.length)return;currentIndex=Math.max(0,Math.min(filtered.length-1,currentIndex+delta));state.currentId=filtered[currentIndex].id;saveState();render();window.scrollTo({top:els.card.offsetTop-10,behavior:'smooth'}); }
function jumpToId() { const id=Number(els.jumpInput.value);const idx=filtered.findIndex(q=>q.id===id);if(idx>=0){currentIndex=idx;state.currentId=id;saveState();render();setMessage(`No.${id}へ移動しました。`);}else setMessage('現在の絞り込み条件では、その番号は表示されていません。',true); }
function backupObject() { return {app:'pharm201-pwa',version:BACKUP_VERSION,exportedAt:new Date().toISOString(),questionCount:QUESTIONS.length,dataHash:DATA_HASH,state:JSON.parse(JSON.stringify(state))}; }
function validateBackup(data) { if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('JSON形式が正しくありません。');if(data.app!=='pharm201-pwa')throw new Error('このアプリのバックアップではありません。');if(data.version===2&&data.state)return sanitizeState(data.state);if(data.version===1&&data.progress){const d=defaultState();d.progress=sanitizeProgress(data.progress);d.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id));return d;}throw new Error('対応していないバックアップ形式です。'); }
function exportBackup() { const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`薬理学201問_学習記録_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('バックアップを書き出しました。'); }
async function importBackup(file) { try{state=validateBackup(JSON.parse(await file.text()));syncControls();saveState();applyFilters({preserveCurrent:true});setMessage('バックアップを読み込みました。');}catch(e){setMessage(`読み込めませんでした：${e.message}`,true);}finally{els.importInput.value='';} }
function setMessage(text,error=false) { els.message.textContent=text;els.message.style.color=error?'var(--danger)':''; }
function syncControls() { els.search.value=state.search;els.status.value=state.statusFilter;els.category.value=state.category;els.order.value=state.order; }
function populateCategories() { [...validCategories].sort((a,b)=>a.localeCompare(b,'ja')).forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;els.category.appendChild(o);}); }
function resetFilters() { state.search='';state.statusFilter='all';state.category='all';state.order='number';state.currentId=1;syncControls();applyFilters({preserveCurrent:false,preferredIndex:0}); }

els.toggle.addEventListener('click',toggleAnswer);els.knownButton.addEventListener('click',()=>judge('known'));els.unknownButton.addEventListener('click',()=>judge('unknown'));els.prev.addEventListener('click',()=>move(-1));els.next.addEventListener('click',()=>move(1));els.jumpButton.addEventListener('click',jumpToId);els.jumpInput.addEventListener('keydown',e=>{if(e.key==='Enter')jumpToId();});
els.search.addEventListener('input',()=>{state.search=els.search.value;applyFilters({preserveCurrent:false,preferredIndex:0});});els.status.addEventListener('change',()=>{state.statusFilter=els.status.value;applyFilters({preserveCurrent:false,preferredIndex:0});});els.category.addEventListener('change',()=>{state.category=els.category.value;applyFilters({preserveCurrent:false,preferredIndex:0});});els.order.addEventListener('change',()=>{state.order=els.order.value;applyFilters({preserveCurrent:false,preferredIndex:0});});els.reshuffle.addEventListener('click',()=>{state.order='shuffle';state.shuffleIds=makeShuffle(QUESTIONS.map(q=>q.id));state.currentId=state.shuffleIds[0];syncControls();applyFilters({preserveCurrent:true});});els.resetFilters.addEventListener('click',resetFilters);els.exportButton.addEventListener('click',exportBackup);els.importInput.addEventListener('change',()=>{const f=els.importInput.files&&els.importInput.files[0];if(f)importBackup(f);});els.resetButton.addEventListener('click',()=>{if(confirm('学習記録をすべて消去しますか？')){state.progress={};saveState();applyFilters({preserveCurrent:true});setMessage('学習記録を消去しました。');}});

if(QUESTIONS.length!==QUESTION_COUNT||validIds.size!==QUESTION_COUNT){document.body.innerHTML='<main class="app"><section class="panel empty"><h1>データ読込エラー</h1><p>問題データが201問ではありません。</p></section></main>';throw new Error('Question data integrity failure');}
populateCategories();syncControls();updateStats();applyFilters({preserveCurrent:true});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>setMessage('オフライン機能の登録に失敗しました。',true)));
window.__APP_TEST__={filterQuestions,makeShuffle,validPermutation,backupObject,validateBackup,getSequence:()=>filtered.map(q=>q.id),getState:()=>JSON.parse(JSON.stringify(state)),getCurrent:()=>filtered[currentIndex]?.id||null,storageKey:STORAGE_KEY,dataHash:DATA_HASH,ready:true};
})();
